import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Link from "next/link";
import LoginButton from "./LoginButton"
import { getServerSession } from "next-auth";
import {authOptions} from "@/pages/api/auth/[...nextauth]"
import { useState } from "react";
import { cookies } from 'next/headers'
import DarkMode from './darkmode'

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  const user = await getServerSession(authOptions);
  console.log('user',user);
  let res = cookies().get('mode');
  console.log('res',res?.value);
  
  
  return (
    <html lang="en">
      <body className={ res!= undefined && res?.value === 'dark' ? 'darkMode' : 'lightMode'}>
        <div className="navbar">
          <Link className="linkTag" href={"/"}>HOME</Link>
          <Link className="linkTag" href={"/list"}>LIST</Link>
          <Link className="linkTag" href={"/write"}>글쓰기</Link>
        </div>
        {
          user === null ? <LoginButton status="로그인"></LoginButton> : <LoginButton status="로그아웃"></LoginButton>
        }
        
        <DarkMode mode={res?.value}/>
        {children}
      </body>
    </html>
  );
}
